apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: argocd
  labels:
    app: guestbook
    managed-by: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mo-norant/devoteam-argocd-presentation
    targetRevision: HEAD
    path: manifests/guestbook
  destination:
    server: https://kubernetes.default.svc
    namespace: guestbook
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

