apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: guestbook

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml

commonLabels:
  app: guestbook
  managed-by: argocd

