apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingpong
  namespace: pingpong
  labels:
    app: pingpong
    managed-by: argocd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pingpong
  template:
    metadata:
      labels:
        app: pingpong
        version: "v1.0.0"
    spec:
      containers:
      - name: pingpong
        image: hashicorp/http-echo:latest
        args:
          - -text=hello world
        ports:
        - containerPort: 8080
          protocol: TCP
          name: http
        resources:
          requests:
            memory: "32Mi"
            cpu: "50m"
          limits:
            memory: "64Mi"
            cpu: "100m"

