apiVersion: v1
kind: Service
metadata:
  name: pingpong
  namespace: pingpong
  labels:
    app: pingpong
    managed-by: argocd
spec:
  type: ClusterIP
  ports:
  - port: 8081
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: pingpong

